name: manushtech_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  get_storage: ^2.1.1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  intl: ^0.19.0
  http: ^1.2.1
  cached_network_image: ^3.3.1


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

